apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'n8n'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    path: 'argocd/helm/docker-mailserver'
    repoURL: https://github.com/iszymon/home-lab.git
    targetRevision: HEAD
    helm:
      values: |-
        nameOverride: "docker-mailserver"
        fullnameOverride: "docker-mailserver"
        deployment:
          env:
            OVERRIDE_HOSTNAME: mail.edgeofthe.cloud
      persistent_volume_claims:
        # Stores generated configuration files
        # https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-the-docker-datadmsconfig-directory
        mail-config:
          enabled: true
          size: 100Mi
          annotations: {}
          accessModes:
            - ReadWriteOnce
          storageClass:
          selector: {}
        mail-data:
          enabled: true
          existingClaim: ""
          size: 10Gi
          annotations: {}
          accessModes:
            - ReadWriteOnce
          storageClass:
          selector: {}
        mail-state:
          enabled: true
          existingClaim: ""
          size: 1Gi
          annotations: {}
          accessModes:
            - ReadWriteOnce
          storageClass:
          selector: {}
      
        # Store mail logs
        mail-log:
          enabled: true
          existingClaim: ""
          size: 1Gi
          annotations: {}
          accessModes:
            - ReadWriteOnce
          storageClass:
          selector: {}


        