apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-mailserver
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'mail'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    path: 'argocd/helm/docker-mailserver'
    repoURL: https://github.com/iszymon/home-lab.git
    targetRevision: HEAD
    helm:
      values: |-
        nameOverride: "docker-mailserver"
        fullnameOverride: "docker-mailserver"
        deployment:
          env:
            OVERRIDE_HOSTNAME: mail.edgeofthe.cloud
        rspamd:
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations: {}
          host: rspamd.edgeofthe.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
          tls:
            - hosts:
                - rspamd.edgeofthe.cloud
              secretName: tls-wildcard-edgeofthe.cloud
        persistent_volume_claims:
          # Stores generated configuration files
          # https://docker-mailserver.github.io/docker-mailserver/edge/faq/#what-about-the-docker-datadmsconfig-directory
          mail-config:
            enabled: true
            size: 10Mi
            annotations: {}
            accessModes:
              - ReadWriteOnce
            storageClass:
            selector: {}
          mail-data:
            enabled: true
            existingClaim: ""
            size: 10Gi
            annotations: {}
            accessModes:
              - ReadWriteOnce
            storageClass:
            selector: {}
          mail-state:
            enabled: true
            existingClaim: ""
            size: 1Gi
            annotations: {}
            accessModes:
              - ReadWriteOnce
            storageClass:
            selector: {}
        
          # Store mail logs
          mail-log:
            enabled: true
            existingClaim: ""
            size: 1Gi
            annotations: {}
            accessModes:
              - ReadWriteOnce
            storageClass:
            selector: {}


        