apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'minio'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    # https://charts.bitnami.com/bitnami
    repoURL: https://charts.bitnami.com/bitnami
    chart: bitnami/minio
    targetRevision: 2025.3.12
    helm:
      values: |-
        nameOverride: "minio"
        fullnameOverride: "minio"
        auth:
          rootUser: admin
          existingSecret: ""
        provisioning:
          resourcesPreset: "nano
          resources: {}
          policies: []
          users: []
          usersExistingSecrets: []
          groups: []
          buckets: []
        containerPorts:
          api: 9000
          console: 9001
        ingress:
          ingressClassName: "nginx"
          hostname: minio.edgeofthe.cloud
          path: /
          tls: true
          extraTls:
          - hosts:
              - minio.edgeofthe.cloud
            secretName: tls-wildcard-edgeofthe-cloud
