apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'minio'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    # https://charts.bitnami.com/bitnami
    repoURL: https://charts.bitnami.com/bitnami
    chart: bitnami/minio
    targetRevision: 2025.3.12
    helm:
      values: |-
        nameOverride: "minio"
        fullnameOverride: "minio"
        ingress:
          enabled: true
          ingressClassName: "nginx"
          hostname: minio.edgeofthe.cloud
          path: /
          extraTls:
          - hosts:
              - minio.edgeofthe.cloud
            secretName: tls-wildcard-edgeofthe-cloud
