apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'minio'
    server: 'https://kubernetes.default.svc'
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    # https://operator.min.io
    repoURL: https://operator.min.io
    chart: minio-operator
    targetRevision: 4.3.7
    helm:
      values: |-
        nameOverride: minio
        fullnameOverride: minio
        operator:
          replicaCount: 2
