apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nvidia-device-plugin
    server: https://kubernetes.default.svc
  project: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: 0.15.1
    helm:
      values: |-
        nameOverride: nvidia-device-plugin
        fullnameOverride: nvidia-device-plugin
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        runtimeClassName: nvidia
        # Inline config map to avoid external CM dependency
        config:
          map:
            default: |-
              version: v1
              deviceListStrategy: envvar
              flags:
                migStrategy: none
          default: default
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        nodeSelector:
          nvidia.com/gpu.present: "true"
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        dcgmExporter:
          enabled: false
        mpsControlDaemon:
          enabled: false
