# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: edgeofthe-cloud
#   namespace: cert-manager
#   labels:
#     {{- include "common.labels" . | nindent 4 }}
# spec:
#   acme:
#     email: michal.lewandowski1988@gmail.com
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: edgeofthe-cloud-issuer-account-key
#     solvers:
#     - dns01:
#         cloudflare:
#           apiTokenSecretRef:
#             name: cloudflare-api-token-secret
#             key: api-token
