apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: edgeofthe-cloud
  namespace: cert-manager
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: edgeofthe-cloud-issuer-account-key
    solvers:
    - dns01:
        route53:
          region: us-east-1
          accessKeyIDSecretRef:
            name: aws-route53-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-route53-secret
            key: secret-access-key